-- Auto-generated from pre-deploy pg_policies snapshot
-- Restores pre-A2 policies if A2 RLS must be rolled back
BEGIN;
DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT policyname, tablename FROM pg_policies WHERE schemaname='public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END $$;
CREATE POLICY "Service role full access a1 rpc catalog" ON public.a1_rpc_baseline_catalog AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Any authenticated user can insert audit log" ON public.audit_log AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Global admin and company manager can view audit log" ON public.audit_log AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "All authenticated users can delete billing breakdown items" ON public.billing_breakdown_items AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert billing breakdown items" ON public.billing_breakdown_items AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update billing breakdown items" ON public.billing_breakdown_items AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all billing breakdown items" ON public.billing_breakdown_items AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete billing_breakdown_items" ON public.billing_breakdown_items AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert billing_breakdown_items" ON public.billing_breakdown_items AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update billing_breakdown_items" ON public.billing_breakdown_items AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all billing_breakdown_items" ON public.billing_breakdown_items AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Service role full access billing breakdown dup archive" ON public.billing_breakdown_items_duplicate_archive AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can delete billing calculations" ON public.billing_calculations AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert billing calculations" ON public.billing_calculations AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update billing calculations" ON public.billing_calculations AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all billing calculations" ON public.billing_calculations AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete billing_calculations" ON public.billing_calculations AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert billing_calculations" ON public.billing_calculations AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update billing_calculations" ON public.billing_calculations AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all billing_calculations" ON public.billing_calculations AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Service role full access billing dup archive" ON public.billing_calculations_duplicate_archive AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access billing conflict report" ON public.billing_duplicate_conflict_report AS PERMISSIVE FOR ALL TO "service_role" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can delete charging sessions" ON public.charging_sessions AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert charging sessions" ON public.charging_sessions AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update charging sessions" ON public.charging_sessions AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all charging sessions" ON public.charging_sessions AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete charging_sessions" ON public.charging_sessions AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert charging_sessions" ON public.charging_sessions AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update charging_sessions" ON public.charging_sessions AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all charging_sessions" ON public.charging_sessions AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can delete fixed charges" ON public.fixed_charges AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert fixed charges" ON public.fixed_charges AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update fixed charges" ON public.fixed_charges AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all fixed charges" ON public.fixed_charges AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete fixed_charges" ON public.fixed_charges AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert fixed_charges" ON public.fixed_charges AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update fixed_charges" ON public.fixed_charges AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all fixed_charges" ON public.fixed_charges AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can delete import batches" ON public.import_batches AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert import batches" ON public.import_batches AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update import batches" ON public.import_batches AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all import batches" ON public.import_batches AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete import_batches" ON public.import_batches AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert import_batches" ON public.import_batches AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update import_batches" ON public.import_batches AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all import_batches" ON public.import_batches AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All authenticated can read maintenance log" ON public.maintenance_log AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY "Authenticated can delete maintenance log" ON public.maintenance_log AS PERMISSIVE FOR DELETE TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY "Authenticated can insert maintenance log" ON public.maintenance_log AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Authenticated can update maintenance log" ON public.maintenance_log AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY "System can insert notifications" ON public.notifications AS PERMISSIVE FOR INSERT TO PUBLIC WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Users can delete own notifications" ON public.notifications AS PERMISSIVE FOR DELETE TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "Users can read own notifications" ON public.notifications AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "Users can update own notifications" ON public.notifications AS PERMISSIVE FOR UPDATE TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "Authenticated users can manage schedules" ON public.operator_schedules AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY "Authenticated users can view schedules" ON public.operator_schedules AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() IS NOT NULL));
CREATE POLICY "All authenticated users can delete operators" ON public.operators AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert operators" ON public.operators AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update operators" ON public.operators AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all operators" ON public.operators AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete operators" ON public.operators AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert operators" ON public.operators AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update operators" ON public.operators AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all operators" ON public.operators AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can delete rate periods" ON public.rate_periods AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert rate periods" ON public.rate_periods AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update rate periods" ON public.rate_periods AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all rate periods" ON public.rate_periods AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete rate_periods" ON public.rate_periods AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert rate_periods" ON public.rate_periods AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update rate_periods" ON public.rate_periods AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all rate_periods" ON public.rate_periods AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can delete rate structures" ON public.rate_structures AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert rate structures" ON public.rate_structures AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update rate structures" ON public.rate_structures AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all rate structures" ON public.rate_structures AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete rate_structures" ON public.rate_structures AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert rate_structures" ON public.rate_structures AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update rate_structures" ON public.rate_structures AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all rate_structures" ON public.rate_structures AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete shifts" ON public.shifts AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert shifts" ON public.shifts AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can read shifts" ON public.shifts AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can update shifts" ON public.shifts AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can delete stations" ON public.stations AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert stations" ON public.stations AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update stations" ON public.stations AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all stations" ON public.stations AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete stations" ON public.stations AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert stations" ON public.stations AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update stations" ON public.stations AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all stations" ON public.stations AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete system_settings" ON public.system_settings AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert system_settings" ON public.system_settings AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can read system_settings" ON public.system_settings AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can update system_settings" ON public.system_settings AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can delete tax configurations" ON public.tax_configurations AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "All authenticated users can insert tax configurations" ON public.tax_configurations AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "All authenticated users can update tax configurations" ON public.tax_configurations AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "All authenticated users can view all tax configurations" ON public.tax_configurations AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete tax_configurations" ON public.tax_configurations AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert tax_configurations" ON public.tax_configurations AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can update tax_configurations" ON public.tax_configurations AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can view all tax_configurations" ON public.tax_configurations AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can delete user_profiles" ON public.user_profiles AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can insert user_profiles" ON public.user_profiles AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);
CREATE POLICY "Authenticated users can read user_profiles" ON public.user_profiles AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Authenticated users can update user_profiles" ON public.user_profiles AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);
COMMIT;
